name: Meterian vulnerability scan workflow

on: push

jobs:
    meterian_scan:
        name: Meterian client scan
        runs-on: ubuntu-latest
        steps: 
          - name: Checkout
            uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4
          - name: Scan project with the Meterian client
            uses: MeterianHQ/meterian-github-action@v1.0.17
            env:
                METERIAN_API_TOKEN: ${{ secrets.METERIAN_API_TOKEN }}
            with:
                cli_args: "" #[ Meterian CLI Options ]
