name: Meterian vulnerability scan workflow

on: push

jobs:
    meterian_scan:
        name: Meterian client scan
        runs-on: ubuntu-latest
        steps: 
          - name: Checkout
            uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4
          - name: Scan project with the Meterian client
            uses: MeterianHQ/meterian-github-action@v1.0.16
            env:
                METERIAN_API_TOKEN: ${{ secrets.METERIAN_API_TOKEN }}
            with:
                cli_args: "" #[ Meterian CLI Options ]
